### ISSUE TITLE
Would you change domain in CNAME file?

### ISSUE THREAD

**Issue by willard-yuan** [gujiuxiang/gujiuxiang.github.io#1]
Hi @gujiuxiang , I find the file in your CNAME file is interfered with my CNAME and the domain of `yongyuan.name` is directed to your site. Would you like to change domain in CNAME file or just delete the CNAME file if you have no owned domain?

**Comment by gujiuxiang** [comment]
Hi, yongyuan.

Sorry about that, I did not aware of the function of your CNAME file. I 
have already delete it. Thanks again for your sharing.

Jiuxiang

**Comment by willard-yuan** [comment]
Thanks

**Comment by willard-yuan** [comment]
@gujiuxiang But it still exsists: https://github.com/gujiuxiang/gujiuxiang.github.io/blob/master/CNAME. You can change it by other string or simple delete the file. It will do no harm for use.

**Comment by gujiuxiang** [comment]
Sorry, the previous push was failed, pushed the commit again, and the file has been deleted.

**Comment by willard-yuan** [comment]
Thank you. 握爪
